// ========================================
// ALTIGA AGRI SOLUTIONS - PRODUCT DATABASE
// Complete product catalog with full details
// ========================================

const productDatabase = {
    // INSECTICIDES - 21 available products with images
    insecticides: [
        {
            id: 1,
            name: "Combipro",
            technical: "Imidacloprid 23.3% + Tebuconazole 1.3% (24.6%)",
            formulation: "SC (Suspension Concentrate)",
            packSize: "300ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/combipro-430x344.jpg",
            description: "Systemic insecticide with dual action against sucking pests and fungal diseases. Provides long-lasting protection with excellent crop safety.",
            crops: ["Cotton", "Vegetables", "Fruits"],
            pests: ["Whitefly", "Jassids", "Aphids", "Thrips", "Powdery Mildew"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Use protective equipment. Do not apply within 14 days of harvest. Keep away from children and pets.",
            dosage: "0.25% spray solution",
            price: "PKR 950",
            badge: "Best Seller"
        },
        {
            id: 2,
            name: "Lufox",
            technical: "Lambdacyhalothrin 10% + Lufenuron 10% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "100ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/lufox-430x344.jpg",
            description: "Advanced insecticide combining broad-spectrum action with growth regulator. Controls both adult pests and larvae effectively.",
            crops: ["Cotton", "Rice", "Wheat", "Vegetables"],
            pests: ["Bollworms", "Leaf worms", "Jassids", "Whitefly", "Armyworms"],
            application: "300-400ml per acre in 200L water",
            safety: "Toxic to aquatic organisms. Do not contaminate water sources. Store in cool, dry place.",
            dosage: "0.15-0.2% spray solution",
            price: "PKR 420",
            badge: "Popular"
        },
        {
            id: 3,
            name: "Ally",
            technical: "Cypermethrin 10% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: ["250ml", "1 Liter"],
            packPerCarton: [24, 12],
            category: "insecticides",
            image: "images/Insecticide/Ally-430x344.jpg",
            description: "Fast-acting pyrethroid insecticide with quick knockdown effect. Broad-spectrum coverage for multiple pests on various crops.",
            crops: ["Cotton", "Vegetables", "Fruits", "Rice", "Wheat"],
            pests: ["Bollworms", "Aphids", "Jassids", "Thrips", "Spidermites"],
            application: "500-750ml per acre in 200L water",
            safety: "Flammable. Keep away from heat and naked flames. Use only in well-ventilated areas.",
            dosage: "0.25-0.3% spray solution",
            price: "PKR 280-950",
            badge: "Top Rated"
        },
        {
            id: 4,
            name: "Revenant",
            technical: "Abamectin 2% + Methoxyfenozide 8% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "300ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/revenant-430x344.jpg",
            description: "Premium combination targeting sucking and chewing pests. Bio-derived abamectin with excellent residual activity.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Spidermites", "Thrips", "Leaf rollers", "Caterpillars", "Whitefly"],
            application: "500ml per acre in 200L water",
            safety: "Harmful if swallowed. Avoid skin contact. Wear gloves and apron during application.",
            dosage: "0.25% spray solution",
            price: "PKR 1,200",
            badge: "Premium"
        },
        {
            id: 5,
            name: "Bispiro",
            technical: "Bifenthrin 4% + Spirotetramat 20% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "300ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/bispiro-430x344.jpg",
            description: "Combination product for systemic and contact control. Effective against resistant pest populations with novel mode of action.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Whitefly", "Jassids", "Aphids", "Spidermites", "Scales"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Do not spray during flowering. Harmful to bees. Apply in early morning or late evening.",
            dosage: "0.2-0.25% spray solution",
            price: "PKR 1,100",
            badge: "Advanced"
        },
        {
            id: 6,
            name: "Magicate",
            technical: "Nitempyram 20% + Pymetrozine 60% WG/SC",
            formulation: ["WG (Water Dispersible Granules)", "SC (Suspension Concentrate)"],
            packSize: ["60g", "120ml"],
            packPerCarton: [40, 24],
            category: "insecticides",
            image: "images/Insecticide/magicate-430x344.jpg",
            description: "Selective insecticide for sucking pest management. Systemic action combined with contact activity for comprehensive control.",
            crops: ["Cotton", "Vegetables", "Rice", "Wheat"],
            pests: ["Whitefly", "Jassids", "Aphids", "Plant hoppers"],
            application: "60-80g WG per acre or 300-400ml SC in 150-200L water",
            safety: "Non-toxic to beneficial insects at recommended doses. Store away from moisture.",
            dosage: "0.04-0.05% WG solution",
            price: "PKR 380-520",
            badge: "Best Seller"
        },
        {
            id: 7,
            name: "Bazuka",
            technical: "Flonicamid 7.5% + Pyriproxyfen 7.5% SE",
            formulation: "SE (Suspension Emulsion)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/bazuka-430x344.jpg",
            description: "Dual action insecticide targeting aphids and whitefly. Growth regulator component prevents next generation development.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Aphids", "Whitefly", "Mites"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Keep away from fish ponds. Use full protective gear. Wash hands after application.",
            dosage: "0.2% spray solution",
            price: "PKR 680",
            badge: "Recommended"
        },
        {
            id: 8,
            name: "Conquer",
            technical: "Chlorantraniliprole 10% + Chlorfenapyr 10% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "100ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/conquer-430x344.jpg",
            description: "Potent combination for chewing and sucking pest control. Provides systemic and contact action with excellent knock-down.",
            crops: ["Vegetables", "Cotton", "Fruits"],
            pests: ["Bollworms", "Armyworms", "Whitefly", "Jassids"],
            application: "300-400ml per acre in 200L water",
            safety: "Highly toxic. Use with maximum caution. Wear protective gloves, apron and mask.",
            dosage: "0.15-0.2% spray solution",
            price: "PKR 850",
            badge: "Potent"
        },
        {
            id: 9,
            name: "Chloral",
            technical: "Chlorpyrifos 40% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: ["250ml", "1 Liter"],
            packPerCarton: [24, 12],
            category: "insecticides",
            image: "images/Insecticide/chloral-430x344.jpg",
            description: "Broad-spectrum organophosphate insecticide. Strong contact and stomach action for soil and foliage pests.",
            crops: ["Rice", "Wheat", "Vegetables", "Cotton"],
            pests: ["Bollworms", "Stem borers", "Armyworms", "Grasshoppers"],
            application: "1-1.5 liters per acre in 200-300L water",
            safety: "Cholinesterase inhibitor. Do not mix with other pesticides. Antidote: Atropine.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 320-950",
            badge: "Trusted"
        },
        {
            id: 10,
            name: "Curiosity",
            technical: "Chlorfenapyr 360 SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: ["100ml", "200ml", "500ml"],
            packPerCarton: [24, 24, 20],
            category: "insecticides",
            image: "images/Insecticide/curiosity-430x344.jpg",
            description: "Unique insecticide for resistant pest populations. Mitochondrial uncoupler with excellent residual effect.",
            crops: ["Vegetables", "Cotton", "Fruits"],
            pests: ["Whitefly", "Spidermites", "Thrips", "Scales", "Mealybugs"],
            application: "400-500ml per acre in 200L water",
            safety: "Do not inhale vapors. Use in well-ventilated areas. Store away from children.",
            dosage: "0.2% spray solution",
            price: "PKR 650-1,200",
            badge: "Innovation"
        },
        {
            id: 11,
            name: "Custodian",
            technical: "Imidacloprid 17.8% SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/custodian-430x344.jpg",
            description: "Systemic insecticide for seed treatment and foliar spray. Excellent for sucking pest management.",
            crops: ["Rice", "Wheat", "Vegetables", "Cotton"],
            pests: ["Jassids", "Aphids", "Whitefly", "Planthoppers"],
            application: "300-400ml per acre in 150-200L water",
            safety: "Toxic to bees. Do not apply during flowering. Wash fruits before consumption.",
            dosage: "0.15-0.2% spray solution",
            price: "PKR 580",
            badge: "Systemic"
        },
        {
            id: 12,
            name: "Fixor",
            technical: "Fipronil 5% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "100ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/fixor-430x344.jpg",
            description: "Phenylpyrazole insecticide with strong contact and stomach action. Effective against resistant populations.",
            crops: ["Rice", "Wheat", "Vegetables"],
            pests: ["Stem borers", "Leaf folders", "Gall midges", "Army worms"],
            application: "500-750ml per acre in 200L water",
            safety: "Do not apply to water sources. Harmful to aquatic life. Store in cool, dry place.",
            dosage: "0.25-0.375% spray solution",
            price: "PKR 520",
            badge: "Effective"
        },
        {
            id: 13,
            name: "Fixor Super",
            technical: "Fipronil 5% + Imidacloprid 4% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "150ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/fixor-super-430x344.jpg",
            description: "Enhanced fipronil formula with systemic imidacloprid. Superior control for multiple pest types.",
            crops: ["Rice", "Vegetables", "Wheat"],
            pests: ["Stem borers", "Whitefly", "Leaf folders", "Jassids"],
            application: "600-750ml per acre in 200L water",
            safety: "Do not spray within 7 days of harvest. Keep container closed when not in use.",
            dosage: "0.3% spray solution",
            price: "PKR 750",
            badge: "Premium"
        },
        {
            id: 14,
            name: "Ozone",
            technical: "Spinosad 5% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "300ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/ozone-430x344.jpg",
            description: "Bio-organic insecticide derived from natural sources. Excellent for organic farming with minimal residue.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Leaf miners", "Caterpillars", "Thrips", "Fruit flies"],
            application: "500-600ml per acre in 200L water",
            safety: "Safe for beneficial insects. Biodegradable. Use full protective gear.",
            dosage: "0.25% spray solution",
            price: "PKR 1,050",
            badge: "Organic"
        },
        {
            id: 15,
            name: "Profen",
            technical: "Profenofos 50% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/profen-430x344.jpg",
            description: "Organophosphate insecticide with wide spectrum activity. Fast knockdown for chewing pests.",
            crops: ["Cotton", "Vegetables", "Rice"],
            pests: ["Bollworms", "Caterpillars", "Armyworms", "Grasshoppers"],
            application: "400-500ml per acre in 200L water",
            safety: "Toxic substance. Keep away from children. Antidote: Atropine and Pralidoxime.",
            dosage: "0.2% spray solution",
            price: "PKR 420",
            badge: "Broad-spectrum"
        },
        {
            id: 16,
            name: "Synkill",
            technical: "Lambda-cyhalothrin 10% WP",
            formulation: "WP (Wettable Powder)",
            packSize: "250g",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/synkill-430x344.jpg",
            description: "Concentrated pyrethroid powder formulation. Excellent for aerial application and ultra-low volume spraying.",
            crops: ["Cotton", "Vegetables", "Fruits"],
            pests: ["Bollworms", "Jassids", "Aphids", "Thrips"],
            application: "200-250g per acre in 150-200L water",
            safety: "Do not apply in presence of bees. Wear dust mask during application.",
            dosage: "0.1-0.125% spray solution",
            price: "PKR 550",
            badge: "Concentrated"
        },
        {
            id: 17,
            name: "Top Gun",
            technical: "Acetamiprid 20% SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/top-gun-430x344.jpg",
            description: "Neonicotinoid systemic insecticide. Translaminar and vascular movement for sucking pest control.",
            crops: ["Vegetables", "Cotton", "Fruits"],
            pests: ["Aphids", "Whitefly", "Jassids", "Thrips"],
            application: "400-500ml per acre in 200L water",
            safety: "Toxic to bees. Avoid application during flowering. Wash hands thoroughly after use.",
            dosage: "0.2% spray solution",
            price: "PKR 680",
            badge: "Neonicotinoid"
        },
        {
            id: 18,
            name: "Monarca",
            technical: "Emamectin Benzoate 5% WG",
            formulation: "WG (Water Dispersible Granules)",
            packSize: "100g",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/monarca-430x344.jpg",
            description: "Bio-pesticide for caterpillar and mite control. Effective on resistant populations with safety to natural enemies.",
            crops: ["Vegetables", "Cotton", "Fruits"],
            pests: ["Armyworms", "Caterpillars", "Spidermites", "Leaf rollers"],
            application: "100-150g per acre in 200L water",
            safety: "Low toxicity to mammals. Do not apply to flowering crops. Store in dry place.",
            dosage: "0.05-0.075% spray solution",
            price: "PKR 850",
            badge: "Bio-pesticide"
        },
        {
            id: 19,
            name: "Emento",
            technical: "Emamectin Benzoate 1.9% + Chlorfenapyr 9.5% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "200ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/emento-430x344.jpg",
            description: "Combination product for mite and caterpillar control. Unique mode of action for resistance management.",
            crops: ["Vegetables", "Cotton", "Fruits"],
            pests: ["Spidermites", "Caterpillars", "Leaf rollers", "Armyworms"],
            application: "400ml per acre in 200L water",
            safety: "Do not spray flowering plants. Use protective equipment. Store away from children.",
            dosage: "0.2% spray solution",
            price: "PKR 920",
            badge: "Combination"
        },
        {
            id: 20,
            name: "Legacy",
            technical: "Lambdacyhalothrin 4.6% + Tiacloprid 9.1% OD",
            formulation: "OD (Oil Dispersion)",
            packSize: "200ml",
            packPerCarton: 24,
            category: "insecticides",
            image: "images/Insecticide/Legacy-430x344.jpg",
            description: "Modern oil dispersion formulation with dual active ingredients. Superior spreading and penetration.",
            crops: ["Cotton", "Vegetables", "Fruits"],
            pests: ["Jassids", "Whitefly", "Aphids", "Bollworms"],
            application: "500ml per acre in 200L water",
            safety: "Do not apply in extreme heat. Avoid eye contact. Use proper ventilation.",
            dosage: "0.25% spray solution",
            price: "PKR 720",
            badge: "Advanced Technology"
        },
        {
            id: 21,
            name: "Lambada",
            technical: "Lambda-cyhalothrin 2.5% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "insecticides",
            image: "images/Insecticide/Lambada-430x344.jpg",
            description: "High-performance pyrethroid for broad spectrum pest control. Quick knockdown with long residual effect.",
            crops: ["Cotton", "Wheat", "Vegetables"],
            pests: ["Bollworms", "Aphids", "Jassids", "Thrips"],
            application: "400-500ml per acre in 200L water",
            safety: "Flammable. Keep away from heat sources. Do not apply during wind.",
            dosage: "0.2% spray solution",
            price: "PKR 950",
            badge: "Fast Acting"
        }
    ],

    // FUNGICIDES - 7 available products with images
    fungicides: [
        {
            id: 101,
            name: "Castra",
            technical: "Carbendazim 50% WP",
            formulation: "WP (Wettable Powder)",
            packSize: "250g",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/castra-430x344.jpg",
            description: "Systemic benzimidazole fungicide for seed treatment and foliar application. Prevents fungal diseases effectively.",
            crops: ["Wheat", "Rice", "Vegetables", "Cotton"],
            pests: ["Rust", "Blight", "Mildew", "Seed-borne diseases"],
            application: "250-400g per acre in 150-200L water",
            safety: "Do not apply to potato. Use protective gloves. Store away from moisture.",
            dosage: "0.125-0.2% spray solution",
            price: "PKR 420",
            badge: "Best Seller"
        },
        {
            id: 102,
            name: "Aquasorb",
            technical: "Mancozeb 75% WP",
            formulation: "WP (Wettable Powder)",
            packSize: "500g",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/aquasorb-430x344.jpg",
            description: "Contact fungicide with protective action. Excellent for early blight, late blight, and leaf spot diseases.",
            crops: ["Potato", "Vegetables", "Fruits"],
            pests: ["Early Blight", "Late Blight", "Leaf Spot", "Downy Mildew"],
            application: "1-1.5kg per acre in 200-300L water",
            safety: "Do not apply to sulfur sensitive crops. Highly toxic. Wash hands after use.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 480",
            badge: "Protective"
        },
        {
            id: 103,
            name: "Duo-Blast",
            technical: "Azoxystrobin 20% + Chlorothalonil 40% WG",
            formulation: "WG (Water Dispersible Granules)",
            packSize: "300g",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/Duo-Blast-430x344.jpg",
            description: "Combination fungicide with strobilurin and contact action. Preventive and curative properties.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Rust", "Blight", "Powdery Mildew", "Leaf Spots"],
            application: "300-400g per acre in 200L water",
            safety: "Avoid inhalation. Use in well-ventilated area. Do not apply to flowering stage.",
            dosage: "0.15-0.2% spray solution",
            price: "PKR 850",
            badge: "Combination"
        },
        {
            id: 104,
            name: "Evole",
            technical: "Hexaconazole 5% SC",
            formulation: "SC (Suspension Concentrate)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/evole-430x344.jpg",
            description: "Triazole fungicide with systemic properties. Prevents and cures fungal infections with minimal phytotoxicity.",
            crops: ["Vegetables", "Fruits", "Cotton", "Wheat"],
            pests: ["Powdery Mildew", "Rust", "Leaf Spot", "Blight"],
            application: "400-500ml per acre in 200L water",
            safety: "Do not apply within 14 days of harvest. Use protective equipment.",
            dosage: "0.2% spray solution",
            price: "PKR 620",
            badge: "Systemic"
        },
        {
            id: 105,
            name: "Eminent-XL",
            technical: "Propiconazole 25% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/eminent-xl-430x344.jpg",
            description: "Broad-spectrum triazole fungicide. Excellent for rust and powdery mildew in wheat and other crops.",
            crops: ["Wheat", "Barley", "Vegetables", "Fruits"],
            pests: ["Rust", "Powdery Mildew", "Leaf Spot", "Net Blotch"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Do not apply to sulfur-sensitive crops. Flammable liquid. Keep away from heat.",
            dosage: "0.2% spray solution",
            price: "PKR 550",
            badge: "Premium"
        },
        {
            id: 106,
            name: "Metrabin",
            technical: "Mefenoxam 4% + Mancozeb 64% WP",
            formulation: "WP (Wettable Powder)",
            packSize: "500g",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/metrabin-430x344.jpg",
            description: "Systemic and contact fungicide for downy mildew control. Excellent for potato and vegetables.",
            crops: ["Potato", "Vegetables", "Grapes"],
            pests: ["Downy Mildew", "Late Blight", "Damping off"],
            application: "800g-1kg per acre in 200-300L water",
            safety: "Highly toxic. Do not inhale dust. Wear protective gloves and mask.",
            dosage: "0.4-0.5% spray solution",
            price: "PKR 720",
            badge: "Downy Mildew Control"
        },
        {
            id: 107,
            name: "Vindra",
            technical: "Vinclozolin 50% WP",
            formulation: "WP (Wettable Powder)",
            packSize: "250g",
            packPerCarton: 24,
            category: "fungicides",
            image: "images/Fungicide/vindra-430x344.jpg",
            description: "Dicarboximide fungicide for rice diseases. Preventive and curative action on blast and sheath blight.",
            crops: ["Rice", "Vegetables", "Wheat"],
            pests: ["Blast", "Sheath Blight", "Leaf Scald", "Brown Spot"],
            application: "500-600g per acre in 200L water",
            safety: "Do not apply within 21 days of harvest. Store in cool, dry place.",
            dosage: "0.25-0.3% spray solution",
            price: "PKR 480",
            badge: "Rice Specialist"
        }
    ],

    // WEEDICIDES - 4 available products with images
    weedicides: [
        {
            id: 201,
            name: "Encounter",
            technical: "Paraquat 20% SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "weedicides",
            image: "images/Weedicide/encounter-430x344.jpg",
            description: "Non-selective contact herbicide for weed control. Quick action with no soil residue.",
            crops: ["All Crops", "Non-crop areas"],
            pests: ["Broadleaf weeds", "Grass weeds"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Highly toxic. Fatal if swallowed. Use maximum protective equipment.",
            dosage: "0.2-0.25% spray solution",
            price: "PKR 380",
            badge: "Non-selective"
        },
        {
            id: 202,
            name: "Matilda",
            technical: "Glyphosate 41% IPA SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "weedicides",
            image: "images/Weedicide/matilda-430x344.jpg",
            description: "Systemic non-selective herbicide. Effective against perennial and annual weeds with complete kill.",
            crops: ["All Crops", "Orchards"],
            pests: ["Perennial weeds", "Annual weeds"],
            application: "1-1.5 liters per acre in 150-200L water",
            safety: "Apply when rain is not expected. Do not apply to desirable plants.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 450",
            badge: "Systemic"
        },
        {
            id: 203,
            name: "Tonale",
            technical: "2,4-D Amine 50% SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "500ml",
            packPerCarton: 24,
            category: "weedicides",
            image: "images/Weedicide/tonale-430x344.jpg",
            description: "Selective herbicide for broadleaf weed control in cereals. Amine salt formulation for better uptake.",
            crops: ["Wheat", "Rice", "Barley"],
            pests: ["Broadleaf weeds"],
            application: "500-750ml per acre in 150-200L water",
            safety: "Do not apply to legumes. Avoid drift to non-target plants.",
            dosage: "0.25-0.375% spray solution",
            price: "PKR 320",
            badge: "Selective"
        },
        {
            id: 204,
            name: "Tri-Ultra",
            technical: "2,4-D + MCPA + Dicamba (Mixed Salts) SL",
            formulation: "SL (Soluble Liquid)",
            packSize: "500ml",
            packPerCarton: 24,
            category: "weedicides",
            image: "images/Weedicide/Tri-Ultra-430x344.jpg",
            description: "Broad-spectrum selective herbicide combining three herbicides. Covers wider range of broadleaf weeds.",
            crops: ["Wheat", "Rice", "Barley", "Maize"],
            pests: ["Broadleaf weeds", "Thistle", "Docks"],
            application: "600-750ml per acre in 150-200L water",
            safety: "Do not apply to legumes. Keep away from water sources.",
            dosage: "0.3-0.375% spray solution",
            price: "PKR 450",
            badge: "Broad-spectrum"
        }
    ],

    // FERTILIZERS - 9 available products with images
    fertilizers: [
        {
            id: 301,
            name: "Humactiv",
            technical: "Humic Acid 12% + Fulvic Acid 3%",
            formulation: "Liquid Bio-stimulant",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/humactiv-430x344.jpg",
            description: "Organic bio-stimulant enhancing nutrient uptake and root development. Improves soil structure and microbial activity.",
            crops: ["All Crops"],
            pests: ["Nutrient deficiency", "Soil compaction"],
            application: "2-3 liters per acre mixed in 200L water",
            safety: "Non-toxic. Safe for beneficial microorganisms. Store in cool place.",
            dosage: "1-1.5% spray solution",
            price: "PKR 520",
            badge: "Organic"
        },
        {
            id: 302,
            name: "Nourish SOP Powder",
            technical: "Potassium Sulphate 50% + Micronutrients",
            formulation: "Water Soluble Powder",
            packSize: "500g",
            packPerCarton: 24,
            category: "fertilizers",
            image: "images/Fertilizer/Nourish-SOP-Powder-430x344.jpg",
            description: "High-grade potassium fertilizer with incorporated micronutrients. Improves fruit quality and disease resistance.",
            crops: ["Vegetables", "Fruits", "Cotton"],
            pests: ["Potassium deficiency", "Micronutrient deficiency"],
            application: "2-3kg per acre",
            safety: "Non-toxic. Hygroscopic - store in dry conditions.",
            dosage: "0.25-0.3% spray solution if dissolved",
            price: "PKR 380",
            badge: "High Potassium"
        },
        {
            id: 303,
            name: "Nourish SOP Granule",
            technical: "Potassium Sulphate 50% + Micronutrients",
            formulation: "Water Soluble Granules",
            packSize: "5kg",
            packPerCarton: 8,
            category: "fertilizers",
            image: "images/Fertilizer/nourish-plus-sop-granule-430x344.jpg",
            description: "Premium granular potassium fertilizer for high-value crops. Granules dissolve quickly with water.",
            crops: ["Fruits", "Vegetables", "Cotton"],
            pests: ["Potassium deficiency"],
            application: "5-8kg per acre",
            safety: "Non-toxic. Handle with dry hands. Do not inhale dust.",
            dosage: "Soil application",
            price: "PKR 1,200",
            badge: "Premium Grade"
        },
        {
            id: 304,
            name: "Sangral 15-17-18",
            technical: "NPK 15:17:18 with Micronutrients",
            formulation: "Water Soluble Granules",
            packSize: "1kg",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/Sangral-15-17-18-430x344.jpg",
            description: "Balanced NPK fertilizer for general crop nutrition. Excellent for vegetative and fruiting stages.",
            crops: ["All Crops"],
            pests: ["NPK deficiency"],
            application: "2-3kg per acre at different growth stages",
            safety: "Non-toxic. Store away from moisture.",
            dosage: "0.1-0.15% spray solution",
            price: "PKR 420",
            badge: "Balanced Formula"
        },
        {
            id: 305,
            name: "Sangral Mix 14-4-42",
            technical: "NPK 14:4:42 with Micronutrients",
            formulation: "Water Soluble Granules",
            packSize: "1kg",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/sangral-mix-14-4-42-430x344.jpg",
            description: "High potassium NPK blend for fruiting and flowering stages. Promotes quality fruit development.",
            crops: ["Fruits", "Vegetables", "Cotton"],
            pests: ["Potassium deficiency"],
            application: "2-3kg per acre during fruiting stage",
            safety: "Non-toxic. Use gloves when handling.",
            dosage: "0.1-0.15% spray solution",
            price: "PKR 480",
            badge: "High Potassium"
        },
        {
            id: 306,
            name: "Sangral Potassium Sulphate",
            technical: "Potassium Sulphate 51% SOP",
            formulation: "Water Soluble Granules",
            packSize: "1kg",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/sangral-potassium-sulphate-51-430x344.jpg",
            description: "Pure potassium sulphate for quality improvement. Chloride-free suitable for sensitive crops.",
            crops: ["Fruits", "Vegetables", "Grapes"],
            pests: ["Potassium deficiency"],
            application: "2-3kg per acre",
            safety: "Non-toxic. Hygroscopic.",
            dosage: "0.1-0.15% spray solution",
            price: "PKR 550",
            badge: "Chloride-free"
        },
        {
            id: 307,
            name: "Sangral Urea Phosphate",
            technical: "Urea 32% + Phosphate 14% (UP 46)",
            formulation: "Water Soluble Granules",
            packSize: "1kg",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/sangral-urea-phosphate-430x344.jpg",
            description: "High-quality N:P blend for root and shoot development. Acidic fertilizer suitable for high-pH soils.",
            crops: ["Rice", "Wheat", "Vegetables"],
            pests: ["Nitrogen and phosphorus deficiency"],
            application: "2-3kg per acre",
            safety: "Non-toxic. Use gloves.",
            dosage: "0.1-0.15% spray solution",
            price: "PKR 420",
            badge: "Root Developer"
        },
        {
            id: 308,
            name: "Sulfultra",
            technical: "Sulphur 80% Wettable Granules",
            formulation: "WG (Wettable Granules)",
            packSize: "500g",
            packPerCarton: 24,
            category: "fertilizers",
            image: "images/Fertilizer/sulfultra-430x344.jpg",
            description: "Elemental sulphur for micronutrient nutrition and fungal disease prevention. Corrects sulphur deficiency.",
            crops: ["All Crops"],
            pests: ["Sulphur deficiency", "Powdery Mildew prevention"],
            application: "5-10kg per acre or 1kg in 200L water",
            safety: "Non-toxic. Use dust mask during application.",
            dosage: "0.5% spray solution",
            price: "PKR 380",
            badge: "Multi-purpose"
        },
        {
            id: 309,
            name: "WoPro Vit",
            technical: "Liquid Concentrate with Amino Acids and Vitamins",
            formulation: "Liquid Bio-stimulant",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "fertilizers",
            image: "images/Fertilizer/wopro-vit-430x344.jpg",
            description: "Advanced bio-stimulant with amino acids and vitamins. Promotes plant vigor and stress tolerance.",
            crops: ["All Crops"],
            pests: ["Stress conditions", "Nutrient deficiency"],
            application: "2-3 liters per acre in 150-200L water",
            safety: "Non-toxic. Safe for all beneficial organisms.",
            dosage: "1-1.5% spray solution",
            price: "PKR 680",
            badge: "Advanced Formula"
        }
    ],

    // MICRONUTRIENTS - 14 available products with images
    micronutrients: [
        {
            id: 401,
            name: "Algas",
            technical: "Seaweed Extract 10% + Amino Acids 3%",
            formulation: "Liquid Bio-stimulant",
            packSize: "500ml",
            packPerCarton: 24,
            category: "micronutrients",
            image: "images/Micro Nutrients/algas-430x344.jpg",
            description: "Natural seaweed extract with bio-active compounds. Enhances root growth and improves stress tolerance.",
            crops: ["All Crops"],
            pests: ["Growth deficiency", "Stress conditions"],
            application: "2-3ml per liter of water",
            safety: "Non-toxic. Biodegradable. Safe for all crops.",
            dosage: "0.2-0.3% spray solution",
            price: "PKR 420",
            badge: "Natural"
        },
        {
            id: 402,
            name: "Armonika",
            technical: "Potassium 5% + Macro and Micro Nutrients",
            formulation: "Liquid Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/armonika-430x344.jpg",
            description: "Balanced micronutrient formula with potassium. Corrects multiple nutrient deficiencies simultaneously.",
            crops: ["All Crops"],
            pests: ["Multiple nutrient deficiency"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Use protective gloves.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 520",
            badge: "Balanced"
        },
        {
            id: 403,
            name: "Basfoliar",
            technical: "Boron 1% + Calcium 2% + Growth Promoters",
            formulation: "Liquid Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/basfoliar-430x344.jpg",
            description: "Specialized formula for flower and fruit set. Boron and calcium prevent flower drop and fruit cracking.",
            crops: ["Fruits", "Vegetables"],
            pests: ["Boron deficiency", "Flower drop", "Fruit cracking"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic at recommended doses. Avoid overdose.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 620",
            badge: "Blossom Support"
        },
        {
            id: 404,
            name: "Borofix",
            technical: "Boron 1% Chelated Form",
            formulation: "Liquid Chelate",
            packSize: "500ml",
            packPerCarton: 24,
            category: "micronutrients",
            image: "images/Micro Nutrients/borofix-430x344.jpg",
            description: "Highly available chelated boron for quick absorption. Prevents boron deficiency in fruits and vegetables.",
            crops: ["Fruits", "Vegetables", "Grapes"],
            pests: ["Boron deficiency"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Non-toxic. Avoid overdose as boron is toxic at high levels.",
            dosage: "0.25-0.3% spray solution",
            price: "PKR 480",
            badge: "Chelated"
        },
        {
            id: 405,
            name: "Boronium",
            technical: "Boron 2% Organic Complex",
            formulation: "Liquid Concentrate",
            packSize: "500ml",
            packPerCarton: 24,
            category: "micronutrients",
            image: "images/Micro Nutrients/boronium-430x344.jpg",
            description: "Organic boron complex for enhanced absorption and mobility. Better translocation in plants.",
            crops: ["Fruits", "Vegetables", "Cotton"],
            pests: ["Boron deficiency"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Non-toxic. Follow recommended dosage.",
            dosage: "0.25-0.3% spray solution",
            price: "PKR 520",
            badge: "Organic Complex"
        },
        {
            id: 406,
            name: "Cotin-K",
            technical: "Potassium 5% + Trace Elements",
            formulation: "Liquid Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/cotin-k-430x344.jpg",
            description: "Potassium enriched micronutrient solution for fruit quality and plant vigor.",
            crops: ["Fruits", "Vegetables", "Cotton"],
            pests: ["Potassium deficiency"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Store in cool place.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 480",
            badge: "Potassium Rich"
        },
        {
            id: 407,
            name: "Cotin-P",
            technical: "Phosphorus 3% + Micronutrients",
            formulation: "Liquid Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/cotin-p-430x344.jpg",
            description: "Phosphorus and micronutrient blend for root development and energy metabolism.",
            crops: ["All Crops"],
            pests: ["Phosphorus deficiency"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Use protective gloves.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 420",
            badge: "Root Developer"
        },
        {
            id: 408,
            name: "Oro-Cal",
            technical: "Calcium 5% + Boron 0.5% + Growth Factors",
            formulation: "Liquid Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/Oro-Cal-430x344.jpg",
            description: "Premium calcium formula for fruit quality and shelf life improvement. Prevents calcium-related disorders.",
            crops: ["Fruits", "Vegetables"],
            pests: ["Calcium deficiency", "Fruit cracking", "Blossom end rot"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Store away from moisture.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 680",
            badge: "Premium"
        },
        {
            id: 409,
            name: "Sangral CXK New",
            technical: "NPK 0:0:51 + Calcium 2% + Micronutrients",
            formulation: "Water Soluble Concentrate",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/sangral-cxk-new-430x344.jpg",
            description: "Advanced potassium and calcium formula for fruit quality. Balances soil nutrients.",
            crops: ["Fruits", "Vegetables"],
            pests: ["Potassium and calcium deficiency"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Avoid contact with eyes.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 580",
            badge: "Advanced"
        },
        {
            id: 410,
            name: "Sangral High-K",
            technical: "Potassium 25% + Micronutrients",
            formulation: "Water Soluble Liquid",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/sangral-high-k-430x344.jpg",
            description: "High concentration potassium solution for fruiting and flowering stages. Improves sugar content and color.",
            crops: ["Fruits", "Vegetables", "Cotton"],
            pests: ["Potassium deficiency"],
            application: "800-1000ml per acre in 150-200L water",
            safety: "Non-toxic. Store in cool place.",
            dosage: "0.4-0.5% spray solution",
            price: "PKR 650",
            badge: "High Potassium"
        },
        {
            id: 411,
            name: "Sangral High-N",
            technical: "Nitrogen 20% + Growth Stimulants",
            formulation: "Water Soluble Liquid",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/sangral-high-n-430x344.jpg",
            description: "High nitrogen formula for vegetative growth. Promotes lush foliage and rapid plant development.",
            crops: ["All Crops"],
            pests: ["Nitrogen deficiency"],
            application: "800-1000ml per acre in 150-200L water",
            safety: "Non-toxic. Avoid excessive application.",
            dosage: "0.4-0.5% spray solution",
            price: "PKR 480",
            badge: "Growth Booster"
        },
        {
            id: 412,
            name: "Sangral High-P",
            technical: "Phosphorus 15% + Growth Factors",
            formulation: "Water Soluble Liquid",
            packSize: "1 Liter",
            packPerCarton: 12,
            category: "micronutrients",
            image: "images/Micro Nutrients/sangral-high-p-430x344.jpg",
            description: "High phosphorus concentrate for root development and energy production. Promotes early flowering.",
            crops: ["All Crops"],
            pests: ["Phosphorus deficiency"],
            application: "1-1.5 liters per acre in 200L water",
            safety: "Non-toxic. Use protective gloves.",
            dosage: "0.5-0.75% spray solution",
            price: "PKR 520",
            badge: "Root Developer"
        },
        {
            id: 413,
            name: "Sangral Zn",
            technical: "Zinc 2% Chelated Form EDTA",
            formulation: "Liquid Chelate",
            packSize: "500ml",
            packPerCarton: 24,
            category: "micronutrients",
            image: "images/Micro Nutrients/sangral-zn-430x344.jpg",
            description: "Highly available chelated zinc for quick correction of zinc deficiency. Promotes enzyme activity.",
            crops: ["All Crops"],
            pests: ["Zinc deficiency"],
            application: "400-500ml per acre in 150-200L water",
            safety: "Non-toxic at recommended doses. Do not overdose.",
            dosage: "0.25-0.3% spray solution",
            price: "PKR 420",
            badge: "Chelated"
        },
        {
            id: 414,
            name: "Turbo Root WG",
            technical: "Mycorrhizal Fungi + Beneficial Bacteria + Growth Hormones",
            formulation: "WG (Water Dispersible Granules)",
            packSize: "100g",
            packPerCarton: 24,
            category: "micronutrients",
            image: "images/Micro Nutrients/turbo-root-wg-430x344.jpg",
            description: "Bio-active root enhancer with beneficial microorganisms. Improves nutrient uptake and disease suppression.",
            crops: ["All Crops"],
            pests: ["Poor root development", "Soil-borne diseases"],
            application: "100-150g per acre in 200L water",
            safety: "Non-toxic. Biodegradable. Safe for beneficial organisms.",
            dosage: "0.05-0.075% spray solution",
            price: "PKR 750",
            badge: "Bio-organic"
        }
    ],

    // ADJUVANTS - 1 available product with image
    adjuvants: [
        {
            id: 501,
            name: "Vintre",
            technical: "Surfactant + Sticker Complex 43% EC",
            formulation: "EC (Emulsifiable Concentrate)",
            packSize: "250ml",
            packPerCarton: 24,
            category: "adjuvants",
            image: "images/Adjuvants/Vintre-430x344.jpg",
            description: "Advanced adjuvant enhancing spray coverage and adherence. Improves pesticide and nutrient absorption.",
            crops: ["All Crops"],
            pests: ["Poor spray coverage"],
            application: "250ml per 100L spray solution (0.25%)",
            safety: "Non-toxic. Use protective gloves. Avoid eye contact.",
            dosage: "0.25% of spray tank",
            price: "PKR 320",
            badge: "Essential"
        }
    ]
};

// Helper function to get all products
function getAllProducts() {
    const all = [];
    Object.values(productDatabase).forEach(category => {
        if (Array.isArray(category)) {
            all.push(...category);
        }
    });
    return all;
}

// Helper function to get products by category
function getProductsByCategory(category) {
    const categoryKey = category.toLowerCase() + 's';
    return productDatabase[categoryKey] || [];
}

// Export for use in HTML
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { productDatabase, getAllProducts, getProductsByCategory };
}
